apiVersion: v1
kind: Service
metadata:
  name: mnist-manage-service
spec:
  selector:
    app: mnist-manage
  ports:
  - name: http
    protocol: TCP
    port: 8088
    targetPort: 8088
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-manage
spec:
  selector:
    matchLabels:
      app: mnist-manage
  replicas: 1
  template:
    metadata:
      labels:
        app: mnist-manage
    spec:
      containers:
      - name: mnist-manage
        image: byeongjokim/mnist-manage
        ports:
        - containerPort: 8088